version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

  commands:
    - mamba install -c conda-forge pixi
    - pixi install
    - pixi run build
    - mkdir $READTHEDOCS_OUTPUT
    - mv _build/html $READTHEDOCS_OUTPUT/html
