version: 2
build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-23.11"
  commands:
    - mamba install -c conda-forge pixi
    - pixi install
    - pixi run build
    - mkdir $READTHEDOCS_OUTPUT
    - mv _build/html $READTHEDOCS_OUTPUT/html
